name: Build and Deploy API Image

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.prayujt.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 \
          -t docker.prayujt.com/distributed-streaming-api \
          -f api/Dockerfile \
          api/ \
          --push

      - name: Request Redeployment
        run: |
          sleep 5; curl -X POST https://deploy.prayujt.com \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"namespace":"distributed-streaming", "deploymentName":"distributed-streaming-api"}'
